export const estadiosReferenciaSemilla = [
  { id: 'estadio-semilla-108', idEstadio: 108, codigo: 'BQ1', nombre: 'Barbecho Quimico 1', ordenCronologico: 4, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-109', idEstadio: 109, codigo: 'Si', nombre: 'Siembra', ordenCronologico: 9, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-111', idEstadio: 111, codigo: 'Pr2', nombre: 'Proteccion 1', ordenCronologico: 12, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-112', idEstadio: 112, codigo: 'COS', nombre: 'Cosecha', ordenCronologico: 26, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-113', idEstadio: 113, codigo: 'BM1', nombre: 'Barbecho Mecanico 1', ordenCronologico: 1, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-114', idEstadio: 114, codigo: 'BM2', nombre: 'Barbecho Mecanico 2', ordenCronologico: 2, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-115', idEstadio: 115, codigo: 'BQ2', nombre: 'Barbecho Quimico 2', ordenCronologico: 5, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-116', idEstadio: 116, codigo: 'BQ3', nombre: 'Barbecho Quimico 3', ordenCronologico: 6, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-117', idEstadio: 117, codigo: 'Pr1', nombre: 'Preemergente', ordenCronologico: 10, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-118', idEstadio: 118, codigo: 'FERT1', nombre: 'Fertilizacion 1', ordenCronologico: 11, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-119', idEstadio: 119, codigo: 'Pr3', nombre: 'Proteccion 2', ordenCronologico: 19, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-120', idEstadio: 120, codigo: 'FERT2', nombre: 'Fertilizacion 2', ordenCronologico: 20, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-121', idEstadio: 121, codigo: 'Pr4', nombre: 'Proteccion 3', ordenCronologico: 21, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-122', idEstadio: 122, codigo: 'Pr5', nombre: 'Proteccion 4', ordenCronologico: 23, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-123', idEstadio: 123, codigo: 'EMB', nombre: 'Embolsado', ordenCronologico: 27, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-124', idEstadio: 124, codigo: 'Pr6', nombre: 'Proteccion 5', ordenCronologico: 24, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-125', idEstadio: 125, codigo: 'BQ4', nombre: 'Barbecho Quimico 4', ordenCronologico: 7, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-126', idEstadio: 126, codigo: 'Pr7', nombre: 'Proteccion 6', ordenCronologico: 25, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-127', idEstadio: 127, codigo: 'LE1', nombre: 'Labores Especiales 1', ordenCronologico: 22, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-128', idEstadio: 128, codigo: 'BM3', nombre: 'Barbecho Mecanico 3', ordenCronologico: 3, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-129', idEstadio: 129, codigo: 'BQ5', nombre: 'Barbecho Quimico 5', ordenCronologico: 8, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-130', idEstadio: 130, codigo: 'CORT1', nombre: 'Corte 1', ordenCronologico: 13, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-131', idEstadio: 131, codigo: 'CORT2', nombre: 'Corte 2', ordenCronologico: 14, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-132', idEstadio: 132, codigo: 'CORT3', nombre: 'Corte 3', ordenCronologico: 15, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-133', idEstadio: 133, codigo: 'CORT4', nombre: 'Corte 4', ordenCronologico: 16, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-134', idEstadio: 134, codigo: 'CORT5', nombre: 'Corte 5', ordenCronologico: 17, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-135', idEstadio: 135, codigo: 'CORT6', nombre: 'Corte 6', ordenCronologico: 18, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-136', idEstadio: 136, codigo: 'Pr8', nombre: 'Proteccion 7', ordenCronologico: 26, activo: true, origen: 'semilla' as const },
  { id: 'estadio-semilla-137', idEstadio: 137, codigo: 'LE2', nombre: 'Labores Especiales 2', ordenCronologico: 23, activo: true, origen: 'semilla' as const },
].sort((a, b) => a.ordenCronologico - b.ordenCronologico || a.idEstadio - b.idEstadio);
