import express from 'express';
import cors from 'cors';
import bodyParser from 'body-parser';
import homeRuta from './routes/home';
import usuariosRuta from './routes/usuarios';
import authRuta from './routes/auth';
import paisesRuta from './routes/paises';
import cultivosRuta from './routes/cultivos';
import camposRuta from './routes/campos';
import lotesRuta from './routes/lotes';
import laboresRuta from './routes/labores';
import analisisSueloRuta from './routes/analisisSuelo';
import avancesSiembraRuta from './routes/avancesSiembra';
import avancesCosechaRuta from './routes/avancesCosecha';
import monitoreosRuta from './routes/monitoreos';
import sincronizacionRuta from './routes/sincronizacion';
import erpRuta from './routes/erp';
import adminIntegracionErpRuta from './routes/adminIntegracionErp';
import adminUsuariosCamposRuta from './routes/adminUsuariosCampos';
import adminEmpresasErpRuta from './routes/adminEmpresasErp';
import planificacionRuta from './routes/planificacion';
import preciosReferenciaRuta from './routes/preciosReferencia';
import gastosComercialesReferenciaRuta from './routes/gastosComercialesReferencia';
import conceptosGastosComercialesRuta from './routes/conceptosGastosComerciales';
import destinosVentaRuta from './routes/destinosVenta';
import laboresReferenciaRuta from './routes/laboresReferencia';
import insumosPlanificacionRuta from './routes/insumosPlanificacion';
import camposPlanificacionRuta from './routes/camposPlanificacion';
import lotesPlanificacionRuta from './routes/lotesPlanificacion';
import { manejadorErrores } from './middleware/manejadorErrores';
import { autenticacionBasica } from './middleware/autenticacion';
import { requierePermiso } from './middleware/permisos';

const app = express();
app.use(cors());
app.use(bodyParser.json());

app.use('/home', homeRuta);
app.use('/auth', authRuta);
app.use('/usuarios', autenticacionBasica, usuariosRuta);
app.use('/paises', autenticacionBasica, paisesRuta);
app.use('/cultivos', autenticacionBasica, cultivosRuta);
app.use('/campos', autenticacionBasica, camposRuta);
app.use('/lotes', autenticacionBasica, lotesRuta);
app.use('/labores', autenticacionBasica, laboresRuta);
app.use('/analisis-suelo', autenticacionBasica, analisisSueloRuta);
app.use('/avances-siembra', autenticacionBasica, avancesSiembraRuta);
app.use('/avances-cosecha', autenticacionBasica, avancesCosechaRuta);
app.use('/monitoreos', autenticacionBasica, monitoreosRuta);
app.use('/sincronizacion', sincronizacionRuta);
app.use('/erp', autenticacionBasica, requierePermiso('erp:leer'), erpRuta);
app.use('/admin/integracion-erp', autenticacionBasica, requierePermiso('erp:configurar'), adminIntegracionErpRuta);
app.use('/admin/asignaciones', autenticacionBasica, requierePermiso('usuarios:asignar-campos'), adminUsuariosCamposRuta);
app.use('/admin/empresas-erp', autenticacionBasica, requierePermiso('erp:configurar'), adminEmpresasErpRuta);
app.use('/planificacion', autenticacionBasica, planificacionRuta);
app.use('/precios-referencia', autenticacionBasica, preciosReferenciaRuta);
app.use('/gastos-comerciales-referencia', autenticacionBasica, gastosComercialesReferenciaRuta);
app.use('/conceptos-gastos-comerciales', autenticacionBasica, conceptosGastosComercialesRuta);
app.use('/destinos-venta', autenticacionBasica, destinosVentaRuta);
app.use('/labores-referencia', autenticacionBasica, laboresReferenciaRuta);
app.use('/insumos-planificacion', autenticacionBasica, insumosPlanificacionRuta);
app.use('/campos-planificacion', autenticacionBasica, camposPlanificacionRuta);
app.use('/lotes-planificacion', autenticacionBasica, lotesPlanificacionRuta);

app.use(manejadorErrores);

const port = Number(process.env.PORT || 4000);
app.listen(port, '0.0.0.0', () => {
  console.log(`API ejecutándose en http://localhost:${port}`);
});
